"""esquema multiusuario inicial

Revision ID: 2016beade187
Revises: (ninguna)
Create Date: 2026-09-02 23:57:47.026176
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '2016beade187'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('login_attempts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('ip', sa.String(length=64), nullable=False),
    sa.Column('successful', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('login_attempts', schema=None) as batch_op:
        batch_op.create_index('ix_login_attempts_email_time', ['email', 'created_at'], unique=False)
        batch_op.create_index('ix_login_attempts_ip_time', ['ip', 'created_at'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('must_change_password', sa.Boolean(), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('failed_login_count', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(), nullable=True),
    sa.CheckConstraint("role IN ('user', 'admin')", name='ck_role_valido'),
    sa.CheckConstraint("status IN ('pending', 'active', 'suspended')", name='ck_status_valido'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('app_channel_prefs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('app_name', sa.String(length=64), nullable=False),
    sa.Column('channel', sa.String(length=16), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.CheckConstraint("channel IN ('whatsapp', 'email')", name='ck_channel_valido'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'app_name', 'channel', name='uq_app_channel_pref')
    )
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('actor_user_id', sa.String(length=32), nullable=True),
    sa.Column('actor_email', sa.String(length=320), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('target_user_id', sa.String(length=32), nullable=True),
    sa.Column('target_email', sa.String(length=320), nullable=False),
    sa.Column('detail_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['target_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index('ix_audit_log_created', ['created_at'], unique=False)

    op.create_table('auth_sessions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('csrf_token', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('user_agent', sa.String(length=256), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    with op.batch_alter_table('auth_sessions', schema=None) as batch_op:
        batch_op.create_index('ix_auth_sessions_user', ['user_id'], unique=False)

    op.create_table('notification_channels',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('channel', sa.String(length=16), nullable=False),
    sa.Column('destination', sa.String(length=320), nullable=False),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("channel IN ('whatsapp', 'email')", name='ck_channel_valido'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'channel', name='uq_notification_channel')
    )
    op.create_table('portfolio_closed_positions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('ticker', sa.String(length=16), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'ticker', name='uq_closed_ticker')
    )
    with op.batch_alter_table('portfolio_closed_positions', schema=None) as batch_op:
        batch_op.create_index('ix_portfolio_closed_user', ['user_id'], unique=False)

    op.create_table('portfolio_holdings',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('ticker', sa.String(length=16), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('avg_cost', sa.Float(), nullable=False),
    sa.Column('sector_hint', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('avg_cost >= 0', name='ck_costo_no_negativo'),
    sa.CheckConstraint('quantity > 0', name='ck_cantidad_positiva'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'ticker', name='uq_holding_ticker')
    )
    with op.batch_alter_table('portfolio_holdings', schema=None) as batch_op:
        batch_op.create_index('ix_portfolio_holdings_user', ['user_id'], unique=False)

    op.create_table('portfolio_profiles',
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('horizon', sa.String(length=24), nullable=False),
    sa.Column('tolerance', sa.String(length=24), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('analysis_interval_days', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint(
        "horizon IN ('short_term', 'medium_term', 'long_term')", name='ck_horizon_valido'
    ),
    sa.CheckConstraint(
        "tolerance IN ('conservative', 'moderate', 'aggressive')", name='ck_tolerance_valido'
    ),
    sa.CheckConstraint('analysis_interval_days > 0', name='ck_intervalo_positivo'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('schedules',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('app_name', sa.String(length=64), nullable=False),
    sa.Column('command_key', sa.String(length=128), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('interval_minutes', sa.Integer(), nullable=True),
    sa.Column('cron_expr', sa.String(length=128), nullable=True),
    sa.Column('next_run_at', sa.DateTime(), nullable=True),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("kind IN ('interval', 'cron')", name='ck_kind_valido'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'app_name', 'command_key', name='uq_schedule')
    )
    with op.batch_alter_table('schedules', schema=None) as batch_op:
        batch_op.create_index('ix_schedules_due', ['enabled', 'next_run_at'], unique=False)

    op.create_table('stock_watches',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('match_terms', sa.JSON(), nullable=False),
    sa.Column('exclude_terms', sa.JSON(), nullable=False),
    sa.Column('variants', sa.JSON(), nullable=False),
    sa.Column('colors', sa.JSON(), nullable=False),
    sa.Column('countries', sa.JSON(), nullable=False),
    sa.Column('notify_channels', sa.JSON(), nullable=False),
    sa.Column('gender', sa.String(length=16), nullable=False),
    sa.Column('max_price', sa.String(length=32), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("gender IN ('mens', 'womens', 'unisex')", name='ck_gender_valido'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_stock_watch_nombre')
    )
    with op.batch_alter_table('stock_watches', schema=None) as batch_op:
        batch_op.create_index('ix_stock_watches_user', ['user_id'], unique=False)

    _migrar_job_runs()

    # ### end Alembic commands ###


#: Conversión de los `started_at` / `finished_at` que la versión anterior del
#: dashboard escribía con `sqlite3` en ISO-8601 ("2026-09-02T23:00:00+00:00")
#: al formato que entiende el tipo DATETIME de SQLAlchemy en SQLite
#: ("2026-09-02 23:00:00"). Los valores ya venían en UTC.
def _iso_a_sqlite(columna: str) -> str:
    return (
        "replace("
        f"CASE WHEN {columna} LIKE '%+00:00' "
        f"THEN substr({columna}, 1, length({columna}) - 6) "
        f"ELSE {columna} END, 'T', ' ')"
    )


def _crear_job_runs(nombre: str = "job_runs") -> None:
    op.create_table(
        nombre,
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('user_id', sa.String(length=32), nullable=True),
        sa.Column('app_name', sa.String(length=64), nullable=False),
        sa.Column('command_key', sa.String(length=128), nullable=False, server_default=''),
        sa.Column('command_label', sa.String(length=128), nullable=False),
        sa.Column('args_json', sa.Text(), nullable=False, server_default='[]'),
        sa.Column('log_path', sa.Text(), nullable=False, server_default=''),
        sa.Column('started_at', sa.DateTime(), nullable=False),
        sa.Column('finished_at', sa.DateTime(), nullable=True),
        sa.Column('duration_seconds', sa.Float(), nullable=True),
        sa.Column('status', sa.String(length=16), nullable=False),
        sa.Column('return_code', sa.Integer(), nullable=True),
        sa.Column('trigger', sa.String(length=16), nullable=False, server_default='manual'),
        sa.Column('schedule_id', sa.String(length=32), nullable=True),
        sa.Column('skip_reason', sa.Text(), nullable=True),
        sa.CheckConstraint(
            "status IN ('running', 'success', 'error', 'skipped', 'cancelled')",
            name='ck_status_valido',
        ),
        sa.CheckConstraint("trigger IN ('manual', 'schedule')", name='ck_trigger_valido'),
        sa.ForeignKeyConstraint(['schedule_id'], ['schedules.id'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    with op.batch_alter_table(nombre, schema=None) as batch_op:
        batch_op.create_index('ix_job_runs_user_app', ['user_id', 'app_name', 'id'], unique=False)


def _migrar_job_runs() -> None:
    """Crea `job_runs`, preservando el historial de la versión single-user.

    La tabla anterior la creaba `jobs.py` con `sqlite3` directo, sin las
    columnas multiusuario y con las fechas en ISO-8601. Si existe, se renombra,
    se crea la tabla nueva y se copian las filas convirtiendo las fechas. Las
    ejecuciones heredadas quedan con `user_id = NULL`: no pertenecen a ningún
    usuario y solo las verá el admin como historial previo a la migración.
    """
    bind = op.get_bind()
    tablas = set(sa.inspect(bind).get_table_names())

    if "job_runs" not in tablas:
        _crear_job_runs()
        return

    op.rename_table("job_runs", "job_runs_legacy")
    _crear_job_runs()
    op.execute(
        "INSERT INTO job_runs "
        "(id, user_id, app_name, command_key, command_label, args_json, log_path, "
        " started_at, finished_at, duration_seconds, status, return_code, trigger, "
        " schedule_id, skip_reason) "
        "SELECT id, NULL, app_name, '', command_label, args_json, log_path, "
        f" {_iso_a_sqlite('started_at')}, {_iso_a_sqlite('finished_at')}, "
        " duration_seconds, status, return_code, 'manual', NULL, NULL "
        "FROM job_runs_legacy"
    )
    op.drop_table("job_runs_legacy")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_runs', schema=None) as batch_op:
        batch_op.drop_index('ix_job_runs_user_app')

    op.drop_table('job_runs')
    with op.batch_alter_table('stock_watches', schema=None) as batch_op:
        batch_op.drop_index('ix_stock_watches_user')

    op.drop_table('stock_watches')
    with op.batch_alter_table('schedules', schema=None) as batch_op:
        batch_op.drop_index('ix_schedules_due')

    op.drop_table('schedules')
    op.drop_table('portfolio_profiles')
    with op.batch_alter_table('portfolio_holdings', schema=None) as batch_op:
        batch_op.drop_index('ix_portfolio_holdings_user')

    op.drop_table('portfolio_holdings')
    with op.batch_alter_table('portfolio_closed_positions', schema=None) as batch_op:
        batch_op.drop_index('ix_portfolio_closed_user')

    op.drop_table('portfolio_closed_positions')
    op.drop_table('notification_channels')
    with op.batch_alter_table('auth_sessions', schema=None) as batch_op:
        batch_op.drop_index('ix_auth_sessions_user')

    op.drop_table('auth_sessions')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index('ix_audit_log_created')

    op.drop_table('audit_log')
    op.drop_table('app_channel_prefs')
    op.drop_table('users')
    with op.batch_alter_table('login_attempts', schema=None) as batch_op:
        batch_op.drop_index('ix_login_attempts_ip_time')
        batch_op.drop_index('ix_login_attempts_email_time')

    op.drop_table('login_attempts')
    # ### end Alembic commands ###
